### ISSUE TITLE
HTTP Client

### ISSUE THREAD

**Issue by Al-Muhandis** [risoflora/libsagui#7]
It seems it is possible to use the HTTP client through SAGUI? Is it possible in legacy app? [instead fphttpclient/synapse HTTPSend etc]. Is that true or am I wrong? The main question: is there proxy support #for these feater?

**Comment by silvioprog** [comment]
Hello @Al-Muhandis, the HTTP client isn't supported (yet), but I added a new item + note to the "To-Do" project [here](https://github.com/risoflora/libsagui/projects/1#column-4057124).

The HTTP and SMTP clients are very common today in the server side. Maybe Sagui library could support it too (plus proxy, TLS etc.).

What do you think? :-)

**Comment by Al-Muhandis** [comment]
Yeah, that would be nice. Especially native fphttpcllient with proxy+HTTPS does not work, synapse works, but only in Windows. And Indy too complex and bulky.

**Comment by silvioprog** [comment]
@Al-Muhandis , I have good news to start 2019: this feature will be implemented! :-) Follow the statuses of the [To-Do entries](https://github.com/risoflora/libsagui/projects/1). The HTTP compression is in progress, so as soon as it is done, we will work in the HTTP client, probably using libcurl as core statically linked, to not depends on external shared libraries. Since this issue was attached to the project note at To-Do project, I'm closing it. Thanks for suggesting the feature and happy new year!
